# Generated by Django 3.2.7 on 2021-10-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(blank=True, verbose_name='検索ワード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
            ],
        ),
    ]
