# Generated by Django 3.2.7 on 2021-10-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_area_comment_image_member_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
