# Generated by Django 3.2.7 on 2021-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20211023_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='constituency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
