# Generated by Django 3.2.7 on 2021-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20211027_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inquiry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('prefecture', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.IntegerField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('search_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
